### PR TITLE
Fixing some small bugs

### PR DESCRIPTION
**Pull request by joaorodriguesz**
I found some errors when compiling the project and decided to contribute because I found the project very interesting. Since I'm here, I would like to suggest creating a version of this project in **Maven**. Thank you, I hope I helped.

### CODE REVIEW

**Comment by idiatech** [comment]
I can confirm that the bug is still there and you can't compile

**Comment by joaorodriguesz** [comment]
> I can confirm that the bug is still there and you can't compile

Can you tell me what the bug was?

**Comment by idiatech** [comment]
J'ai résolu le problème. vous devez enlever le commentaire cyrillique qui fait bugguer la compilation et corriger cette partie du code dans BalanceResponse.java
 captchaCredits = **return** json.getDouble("captchaCredits");

**Comment by joaorodriguesz** [comment]
> BalanceResponse.java

Ah, very cool, I didn't use BalanceResponse.java in my project, just these small corrections I made, I was able to compile without errors and use it. Glad you are contributing too : )

**Comment by joaorodriguesz** [comment]
> J'ai résolu le problème. vous devez enlever le commentaire cyrillique qui fait bugguer la compilation et corriger cette partie du code dans BalanceResponse.java captchaCredits = **return** json.getDouble("captchaCredits");

Ah, very cool, I didn't use BalanceResponse.java in my project, just these small corrections I made, I was able to compile without errors and use it. Glad you are contributing too : )

**Comment by anti-captcha** [comment]
Issue is fixed, sorry guys.

**Pull request closed without merging**
